FROM openjdk:17
EXPOSE 7777

WORKDIR /home

ADD jenkinswork/demodocker2/spring-boot-helloworld*.jar /home/jenkinswork/demodocker2/app-demodocker2.jar
ENTRYPOINT ["java","-jar","/home/jenkinswork/demodocker2/app-demodocker2.jar"]